### ISSUE TITLE
Cannot execute buffer_example

### ISSUE THREAD

**Issue by bguil** [fxfactorial/ocaml-nodejs#9]
compilation and installation is OK but in `examples` folder, the command:
`node buffer.jsnode buffer.js`
gives the following error:

```
/Users/guillaum/code/ocaml-nodejs/examples/buffer.js:5769
       /*<<buffer_example.ml 3 13>>*/ jsoo_self.from(jsoo_173316d7),
                                                ^

TypeError: this is not a typed array.
    at Function.from (native)
    at /Users/guillaum/code/ocaml-nodejs/examples/buffer.js:5769:49
    at Object.<anonymous> (/Users/guillaum/code/ocaml-nodejs/examples/buffer.js:5779:3)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by fxfactorial** [comment]
@bguil  I'm not working on this project anymore because it uses `js_of_ocaml`, which I have decided not to work with anymore. In the future I might redo this with `bucklescript`. 

Feel free to create a PR to fix it.

**Comment by bguil** [comment]
Thanks for the quick reply!
I guess that you don't work on ocaml-electron for the same reason, am I right?
I was looking for a simple way to use ocaml in electron app, any advice?

**Comment by fxfactorial** [comment]
@bguil correct, I don't continue work on ocaml-electron because I don't want to associate with `js_of_ocaml` anymore. 

You can pick up from where I left off, or wait until I get back to it using bucklescript, or do it yourself. 

You can let `js_of_ocaml` upstream know that this is the result of alienation of people that put effort towards the `js_of_ocaml` ecosystem.
